[package]
name = "wasabi"
version = "0.0.4"
edition = "2024"
license = "MIT"
authors = ["dijikey"]
categories = ["game-engines", "graphics", "gui", "rendering"]
repository = "https://github.com/dijikey/wasabi"
description = "A simple 3D game engine with a fully customized architecture"
keywords = ["game", "engine", "gamedev", "graphics", "wasabi"]

[features]
default = []

[dependencies]
wasabi-traits = {path = "crates/wasabi-traits"}

log = "0.4.25"

# [target.'cfg(feature = "default")'.dependencies]
# wasabi-win = {path = "crates/wasabi-win"}
# wasabi-renderer = {path="crates/wasabi-renderer"}

[dev-dependencies]
wasabi-renderer = {path="crates/wasabi-renderer"}
wasabi-win = {path = "crates/wasabi-win"}
event-dispatcher = {path="crates/event-dispatcher"}
env_logger = "0.11.5"
